app/config/routes.rb
class AdminConstraint

    def current_user(request)
        User.find_by_id(request.session[:user_id])
    end

    def matches?(request)
        user = current_user(request)
        if user 
            user.is_admin
        else
            false
        end
    end
end

class UserConstraint

    def current_user(request)
        User.find_by_id(request.session[:user_id])
    end

    def matches?(request)
        user = current_user(request)
        user != nil
    end
end


Rails.application.routes.draw do

    localized do
        get 'login', to: 'session#new', as: 'login'

        get 'logout', to: 'session#destroy', as: 'logout'
        post 'auth', to: 'session#create', as: 'auth'

        constraints UserConstraint.new do
            get 'records', to: 'record#index', as: 'record_index'
            get 'record/download', to: 'record#download', as: 'record_download'
            get 'record/update', to: 'record#update', as: 'record_update'
        end

        constraints AdminConstraint.new do
            get 'users', to: 'user#index', as: 'user_index'
            post 'user/create', to: 'user#create', as: 'user_create'
            post 'user/drop', to: 'user#drop', as: 'user_drop'
            post 'user/update', to: 'user#update', as: 'user_update'
        end

        root to: 'home#index'

        #get 'hello', to: 'home#hello'
        #post 'hello', to: 'home#hello'


        match "/404", to: "error#not_found", via: :all
        match "/402", to: "error#not_found", via: :all
        match "/422", to: "error#unacceptable", via: :all
        match "/500", to: "error#internal_error", via: :all
        match "/503", to: "error#internal_error", via: :all

        match '/:url', to: "error#not_found", via: :all, constraints: { url: /.*/ }
    end

end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/app/models/record.rb
class Record < ApplicationRecord

end

app/app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, length: { minimum: 4 }, confirmation: true, on: :create

end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    around_action :set_locale_from_url

    include Pagy::Backend

end

app/app/controllers/error_controller.rb
class ErrorController < ApplicationController

    def not_found
        #render 'not_found', status: 404
        respond_to do |format|
            format.html { render status: 404 }
            format.json { render json: { error: "not-found" }, status: 404 }
        end
    end

    def unacceptable
        respond_to do |format|
            format.html { render status: 422 }
            format.json { render json: { error: "params unacceptable" }, status: 422 }
        end
    end


    def internal_error
        respond_to do |format|
            format.html { render status: 500 }
            format.json { render json: { error: "internal-error" }, status: 500 }
        end
  end

end

app/app/controllers/home_controller.rb
class HomeController < ApplicationController

    #before_filter :set_locale

    def index
        if session[:user_id]
            redirect_to record_index_path
        else
            set_locale
            redirect_to login_path
        end
    end

    def set_locale
        I18n.locale = extract_locale_from_headers
    end

    private

    def extract_locale_from_headers
        request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first.presence || 'en'
    end

end

app/app/controllers/index_controller.rb
class IndexController < ApplicationController

    def index
        render 'index'
    end

    def notfound
        render 'notfound'
    end
end

app/app/controllers/record_controller.rb
class RecordController < ApplicationController

    attr_accessor :search_timestamp, :search_source, :search_destination
    #attr_reader :pagy_nav, :records

    def initialize
        super
        @dir = Rails.configuration.records_dir
    end

    def update
        UpdateRecordsJob.perform_later
        redirect_to record_index_path
    end

    def index
        #@pagy, @records = pagy(Record.all.order(timestamp: :desc))


        search_timestamp = params[:timestamp]
        search_source = params[:source]
        search_destination = params[:destination]

        if search_source != nil
            search_source.gsub!(/[\-()_.+ ]/, '')
        end
        if search_destination != nil
            search_destination.gsub!(/[\-()_.+ ]/, '')
        end

        @pagy_nav, @records = pagy(Record
            .where('timestamp like ?', "%#{search_timestamp}%")
            .where('source like ?', "%#{search_source}%")
            .where('destination like ?', "%#{search_destination}%")
            .order(timestamp: :desc))

        @search_timestamp = search_timestamp
        @search_source = search_source
        @search_destination = search_destination

        render 'index'
    end

    def download
        id = params[:id]
        record = Record.find_by(id: id)
        send_file File.join(@dir, record.filename), :disposition => 'attachment'
    end

end

app/app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
        render layout: false
    end

    def create
        user = User.find_by_username(params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_url
        else
            flash[:alert] = "Username or password is invalid"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end

end

app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    #layout  nil

    def new
        render :layout => false
    end

    def create
        user = User.find_by_email(params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_url
        else
            flash[:alert] = "Email or password is invalid"
            redirect_to "/login"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end

end

app/app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
        @pagy, @users = pagy(User.all.order(name: :desc))
    end

    def create
        user = User.new
        user.is_admin = params[:is_admin]
        user.name = params[:name]
        user.username = params[:username]
        user.password = params[:password]
        user.password_confirmation = params[:password]

        if user.valid?
            user.save
            flash[:notice] = "User record created"
        else
            flash[:alert] = user.errors.full_messages
        end 
        redirect_to user_index_path
    end

    def update
        id = params[:id]
        user = User.find_by(id: id)
        user.is_admin = params[:is_admin]
        user.name = params[:name]
        user.username = params[:username]

        if params[:password] != nil
            user.password = params[:password]
            user.password_confirmation = params[:password]
        end

        if user.valid?
            user.save
            flash[:notice] = "User record updated"
        else
            flash[:alert] = user.errors.full_messages
        end
        redirect_to user_index_path
    end

    def drop
        id = params[:id]
        user = User.find_by(id: id)
        user.destroy
        flash[:notice] = "User record deleted"
        redirect_to user_index_path
    end

end

app/app/helpers/application_helper.rb
module ApplicationHelper

    include Pagy::Frontend

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

end

app/app/helpers/error_helper.rb
module ErrorHelper
end

app/app/helpers/index_helper.rb
module IndexHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
end

app/app/helpers/user_helper.rb
module UserHelper
end

app/app/views/index/index.html.erb
<h4>Lorem Ipsum</h4>

<h5>1.10.32 de Finibus Bonorum et Malorum</h5>

<p>
    Sed ut perspiciatis unde omnis iste natus error sit voluptatem
    accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab
    illo inventore veritatis et quasi architecto beatae vitae dicta sunt
    explicabo.

</p>

app/app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>R2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>

    <nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark mb-4">

        <div class="navbar-brand">
            <i class="fab fa-old-republic fa-lg"></i> R2
        </div>

        <% if current_user %>
            <%= link_to t('records'), record_index_path, class: "nav-link" %>
            <% if current_user.is_admin %>
                <%= link_to t('users'), user_index_path, class: "nav-link" %>
            <% end %>
        <% end %>

        <ul class="nav justify-content-end ml-auto mr-3">

            <li class="nav-item">
                <% if current_user %>
                    <%= link_to current_user.username, logout_path %>
                <% else %>
                    <%= link_to "Login", login_path %>
                <% end %>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <%= yield %>
    </div>

    <div class="container">
        <div class="row">
            <div class="col mt-5">
                <hr class="justify-content-sm-center" />
                <div class="text-center">
                    <small><%= t 'made_by' %> <a href="http://wiki.unix7.org"><%= t 'borodin_oleg' %></a></small>
                </div>
            </div>
        </div>
    </div>

    <%= javascript_pack_tag 'application' %>

</body>

</html>

app/app/views/record/index.html.erb
<div class="container">

    <div class="row justify-content-center">
        <div class="col-10 col-sm-12 col-md-10 mt-sm-3">

            <div class="row">
                <div class="col">
                    <a class="btn btn-primary btn-sm ml-auto float-right mb-3 d-inline-block" href="<%= record_update_path %>" >
                        <span data-toggle="tooltip" data-placement="left" title="<%= I18n.t 'update_records_info' %>">
                            <i class="fas fa-sync" ></i>
                        </span>

                    </a>
                    <h5 class="mb-3"><b><%= t 'records' %></b></h5>
                </div>
            </div>

            <form method="get" action="<%= record_index_path %>">

                <div class="form-row w-75 mb-2">

                    <div class="col">
                        <input type="text" class="form-control form-control-sm" placeholder="<%= I18n.t 'date_time' %>" name="timestamp" value="<%= @search_timestamp %>">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control form-control-sm" placeholder="<%= I18n.t 'source' %>" name="source"  value="<%= @search_source %>">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control form-control-sm" placeholder="<%= I18n.t 'destination' %>" name="destination"  value="<%= @search_destination %>">
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                </div>

            </form>


            <table class="table table-striped table-hover table-sm">

                <thead class="thead-light">
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">timestamp</th>
                        <th scope="col">source</th>
                        <th scope="col">dest</th>
                        <th scope="col">len</th>
                        <th scope="col"><i class="fas fa-file-download"></i></th>

                    </tr>
                </thead>

                <tbody>

                    <% i = @pagy_nav.offset %>
                    <% records = Record.all %>
                    <% @records.each do |item| %>
                        <% i += 1 %>
                    <tr>
                        <td><%= i %></td>

                        <td>
                            <%= item.timestamp %>
                        </td>
                        <td>
                            <%= item.source %>
                        </td>

                        <td>
                            <%= item.destination %>
                        </td>

                        <td>
                            <%= (item.size/16384).to_i %>
                        </td>

                        <td>
                            <a href="<%= record_download_path %>?id=<%= item.id %>" target="_blank">
                                <i class="fas fa-file-download"></i>
                            </a>
                        </td>
                    </tr>
                    <% end %>
                </tbody>

            </table>
            <%== pagy_bootstrap_nav @pagy_nav %>

        </div>
    </div>


</div>

app/app/views/session/new.html.erb
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>R2 Login</title>

    <%= stylesheet_pack_tag 'application', media: 'all' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

</head>

<body>

    <div>
        <nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark mb-4">
            <span class="navbar-text ml-3">
                <i class="fab fa-old-republic fa-lg"></i>
                <%= t 'login' %>
            </span>

            <ul class="nav justify-content-end ml-auto">

                <% locale = I18n.locale %>
                <% I18n.available_locales.each do |locale| %>
                    <li class="nav-item">
                        <% I18n.locale = locale  %>
                        <%= link_to t(locale), login_path, class: "nav-link" %>

                    </li>
                <% end %>
                <% I18n.locale = locale %>

                <li lass="nav-item">
                    <%= link_to t('go_home'), root_path, class: "nav-link" %>
                </li>


            </ul>
        </nav>

        <div class="container">
            <div class="row justify-content-center">
                <div class=" col-8 col-sm-6 col-md-4 border p-4 mt-sm-5 ml-3 mr-3">

                    <form action="<%= auth_path %>" accept-charset="UTF-8" method="post">

                        <div class=" form-group">
                            <label for="username"><%= t 'username' %></label>
                            <input type="text" name="username" id="username" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label for="password"><%= t 'password' %></label>
                            <input type="password" name="password" id="password" class="form-control" />
                        </div>

                        <div class="text-center">
                            <button name="button" type="submit" class="btn btn-primary btn-sm"><%= t 'submit' %></button>
                        </div>

                    </form>

                </div>
            </div>
        </div>

        <% if flash[:alert] %>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-8 col-sm-8 col-md-6 mt-sm-3">
                        <div class="text-center ">
                            <span class="text-danger"><b><%= flash[:alert] %></b></span>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>

        <div class="container">
            <div class="row">
                <div class="col mt-5">
                    <hr class="justify-content-sm-center" />
                    <div class="text-center">
                        <small><%= t 'made_by' %> <a href="http://wiki.unix7.org"><%= t 'borodin_oleg' %></a></small>
                    </div>
                </div>
            </div>
        </div>

    <%= javascript_pack_tag "application" %>

</body>

</html>

app/app/views/user/index.html.erb
<div class="modal fade" id="user-create" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <form method="post" action="<%= user_create_path %>">

                <div class="modal-header">
                    <h5 class="modal-title"><%= t 'create_user' %></h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label for="name"><%= t 'name' %>:</label>
                        <input type="text" class="form-control" name="name" id="name">
                    </div>

                    <div class="form-group">
                        <label for="username"><%= t 'username' %>:</label>
                        <input type="text" class="form-control" name="username" id="username">
                    </div>

                    <div class="form-group">
                        <label for="password"><%= t 'password' %>:</label>
                        <input type="password" class="form-control" name="password" id="password">
                    </div>

                    <div class="form-group">
                        <label for="password_confirmation"><%= t 'password_confirmation' %>:</label>
                        <input type="password" class="form-control" name="password_confirmation" id="password_confirmation">
                    </div>

                    <div class="form-check">
                        <input type="checkbox" name="is_admin" id="is_admin" />
                        <label class="form-check-label" for="is_admin"> <%= t 'as_admin' %></label>
                    </div>

                </div>


                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><%= t 'close' %></button>
                    <button type="submit" class="btn btn-sm btn-primary"><%= t 'create' %></button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-10 col-sm-12 col-md-8 mt-sm-3">

            <% if flash[:alert] %>
                <div class="alert alert-danger" role="alert" id="alert">

                    <button type="button" class="close" data-dismiss="alert">
                        <span>&times;</span>
                    </button>

                    <h5><%= t 'Error' %></h5>

                    <ol>
                        <% flash[:alert].each do |item| %>
                            <li><%= item %></li>
                        <% end %>
                    </ol>

                </div>
            <% end %>

            <% if flash[:notice] %>

                <div class="alert alert-success" role="alert" id="notice">
                    <button type="button" class="close" data-dismiss="notice">
                        <span>&times;</span>
                    </button>

                    <%= flash[:notice] %>
                </div>
            <% end %>

            <div class="row">
                <div class="col">
                    <div class="btn btn-primary btn-sm ml-auto float-right mb-3 d-inline-block" data-toggle="modal" data-target="#user-create">
                        <i class="fas fa-plus"></i>
                    </div>
                    <h5 class="mb-3"><b><%= t 'users' %></b></h5>
                </div>
            </div>

            <table class="table table-striped table-hover table-sm">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">name</th>
                        <th scope="col">login</th>
                        <th scope="col">upd</th>
                        <th scope="col">del</th>
                    </tr>
                </thead>

                <tbody>
                    <% i = @pagy.offset %>
                    <% @users.each do |u| %>
                    <tr>
                        <td>
                            <%= i += 1 %>
                        </td>
                        <td>
                            <% if u.is_admin %>
                            <i class="fas fa-star"></i>
                            <% end %>
                            <%= u.name %>
                        </td>
                        <td>
                            <%= u.username %>
                        </td>

                        <td>

                            <div class="modal fade" id="user-update-<%= u.id %>" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">

                                        <form method="post" action="<%= user_update_path %>">

                                            <div class="modal-header">
                                                <h5 class="modal-title"><%= t 'update_user' %> <%= u.username %></h5>
                                                <button type="button" class="close" data-dismiss="modal">
                                                    <span>&times;</span>
                                                </button>
                                            </div>

                                            <div class="modal-body">

                                                <input type="hidden" name="id" value="<%= u.id %>" />

                                                <div class="form-group">
                                                    <label for="name"><%= t 'name' %>:</label>
                                                    <input type="text" class="form-control" name="name" id="name" value="<%= u.name %>">
                                                </div>

                                                <div class="form-group">
                                                    <label for="username"><%= t 'username' %>:</label>
                                                    <input type="text" class="form-control" name="username" id="username" value="<%= u.username %>">
                                                </div>

                                                <div class="form-group">
                                                    <label for="password"><%= t 'new_password' %>:</label>
                                                    <input type="password" class="form-control" name="password" id="password">
                                                </div>

                                                <div class="form-group">
                                                    <label for="password_confirmation"><%= t 'new_password_confirmation' %>:</label>
                                                    <input type="password" class="form-control" name="password_confirmation" id="password_confirmation">
                                                </div>


                                                <div class="form-check">
                                                    <input type="checkbox" name="is_admin" id="is_admin" />
                                                    <label class="form-check-label" for="is_admin"> <%= t 'login_as_admin' %></label>
                                                </div>
                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><%= t 'close' %></button>
                                                <button type="submit" class="btn btn-sm btn-primary"><%= t 'update' %></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <div class="btn btn-sm btn-light" data-toggle="modal" data-target="#user-update-<%= u.id %>">
                                <i class="far fa-edit"></i>
                            </div>

                        </td>

                        <td>
                            <div class="modal fade" id="user-drop-<%= u.id %>" tabindex="-1" role="dialog">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">

                                        <form method="post" action="<%= user_drop_path %>">

                                            <div class="modal-header">
                                                <h5 class="modal-title"><%= t 'drop_user' %> <%= u.username %></h5>
                                                <button type="button" class="close" data-dismiss="modal">
                                                    <span>&times;</span>
                                                </button>
                                            </div>

                                            <div class="modal-body">

                                                <input type="hidden" name="id" value="<%= u.id %>" />

                                                <div class="form-check">
                                                    <%= check_box_tag :confirmation %>
                                                    <label class="form-check-label" for="confirmation"> <%= t 'i_agree_to_this_action' %></label>
                                                </div>

                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal"><%= t 'close' %></button>
                                                <button type="submit" class="btn btn-sm btn-primary"><%= t 'drop' %></button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>

                            <div class="btn btn-sm btn-light" data-toggle="modal" data-target="#user-drop-<%= u.id %>">
                                <i class="far fa-trash-alt"></i>
                            </div>

                        </td>

                    </tr>
                    <% end %>
                </tbody>

            </table>

            <%== pagy_bootstrap_nav @pagy %>

        </div>
    </div>
</div>